### PR TITLE
very basic form and activity list

### LINKED ISSUE #14: Creating adding activities page
creating the form to enter an activity and div to display all the activities

### PR DESCRIPTION
**Pull request by aflam745**
Created very basic activity form and list of activities entered.

Closes #14

### CODE REVIEW

**Comment by khazixi** [comment]
I added the CSS that Andrew needed and refactored a lot of the form data code to use less hard coded values

**Review by khazixi — APPROVED** [review]
This is good. I haven't really looked but I just know it is

**Comment by rwinfield** [comment]
Looks good

**Review by rwinfield — APPROVED** [review]
All looks good

**Pull request merged**
